### ISSUE TITLE
Error while building

### ISSUE THREAD

**Issue by fetag** [mausch/docker-mono-web#1]
There is an error message while building, build failed.
--
Sending build context to Docker daemon  6.656kB
Step 1/7 : FROM mono:4.0.1
4.0.1: Pulling from library/mono
52747b744e22: Pull complete
a3ed95caeb02: Pull complete
bcdfa5245946: Pull complete
50df7d9be93c: Pull complete
5fc529821ea0: Pull complete
Digest: sha256:3e42512b7f1b3dfdea7583ae175abca36942632b1c0cf1100569a08598d4641a
Status: Downloaded newer image for mono:4.0.1
 ---> 2cd6319b88fe
Step 2/7 : RUN apt-get update &&   apt-get install -y mono-fastcgi-server4=3.8-0xamarin2 nginx=1.2.1-2.2+wheezy3 supervisor=3.0a8-1.1+deb7u1
 ---> Running in 9651ed83203c
Get:1 http://security.debian.org wheezy/updates Release.gpg [1554 B]
Get:2 http://security.debian.org wheezy/updates Release [39.0 kB]
Get:3 http://security.debian.org wheezy/updates/main amd64 Packages [685 kB]
Get:4 http://httpredir.debian.org wheezy Release.gpg [2373 B]
Get:5 http://download.mono-project.com wheezy/snapshots/4.0.0 Release.gpg [473 B]
Get:6 http://download.mono-project.com wheezy/snapshots/4.0.0 Release [7531 B]
Get:7 http://httpredir.debian.org wheezy-updates Release.gpg [1554 B]
Get:8 http://httpredir.debian.org wheezy Release [191 kB]
Get:9 http://download.mono-project.com wheezy/snapshots/4.0.0/main amd64 Packages [55.6 kB]
Get:10 http://httpredir.debian.org wheezy-updates Release [155 kB]
Get:11 http://httpredir.debian.org wheezy/main amd64 Packages [7634 kB]
Get:12 http://httpredir.debian.org wheezy-updates/main amd64 Packages [7481 B]
Fetched 8781 kB in 5s (1466 kB/s)
Reading package lists...
W: Conflicting distribution: http://download.mono-project.com wheezy/snapshots/4.0.0 Release (expected wheezy/snapshots but got wheezy)
Reading package lists...
Building dependency tree...
Reading state information...
E: Version '1.2.1-2.2+wheezy3' for 'nginx' was not found
The command '/bin/sh -c apt-get update &&   apt-get install -y mono-fastcgi-server4=3.8-0xamarin2 nginx=1.2.1-2.2+wheezy3 supervisor=3.0a8-1.1+deb7u1' returned a non-zero code: 100

**Comment by mausch** [comment]
Hi @fetag the stuff in this repo is really old and most likely obsolete by now. I'll delete this repo soon.

**Comment by fetag** [comment]
Hi mausch,

Got it. Thanks for your reply.
